export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST'
export const FETCH_ITEMS_FAILURE = 'FETHC_ITEMS_FAILURE'
export const FETCH_ITEMS_SUCCESS = 'FETHC_ITEMS_SUCCESS'

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST'
export const FETCH_ITEM_FAILURE = 'FETHC_ITEM_FAILURE'
export const FETCH_ITEM_SUCCESS = 'FETHC_ITEM_SUCCESS'

export const FETCH_FAVOURITES_REQUEST = 'FETCH_FAVOURITES_REQUEST'
export const FETCH_FAVOURITES_FAILURE = 'FETCH_FAVOURITES_FAILURE'
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS'

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
